#!/bin/bash

all_js_files=$(git diff --cached --diff-filter=d --name-only | grep *.js$)
linter_exit_code=0
cd registry-backend-api && npm run lint-js:fix 
linter_exit_code=$?
git add -f $all_js_files

if [ $linter_exit_code -ne 0 ]
then
    echo "❌ Linter errors have occurred."
    exit 1
else
   echo "✔ Eslint and Stylelint did not find any errors"
   exit 0
fi