ENV: dev
REGION: ${self:custom.region}
DB_NAME: 'postgres'
DB_HOST: '52.206.80.247'
DB_PORT: '5432'
DB_USER: 'postgres'
DB_PASSWORD: 'redgistry-dev'
AUTH_APPLICATIONID: 2
AUTH_SCOPES: 'read write follow'
DB_TABLE_USERS: 'users'
DB_TABLE_AUTH_ACCESS_TOKENS: 'oauth_access_tokens'

IS_SOCIAL_DEFAULT_PASSWORD: 'IS_SOCIAL@12345'
AUTH0_CLIENT_ID: 'GAA0GXPm9gsPrIIpLKCtsJziCIqAiHeY'
AUTH0_CONNECTION: 'Username-Password-Authentication'
AUTH0_API_BASE_URL: 'https://dev-0vf2g2usonnwi44r.us.auth0.com'
ISSUER_BASE_URL: 'https://dev-0vf2g2usonnwi44r.us.auth0.com'
AUTH0_CLIENT_SECRET: 'lNok8wyqiFW_QWxMg4wBJRtKpHgZZjJ2hcvIuKHB22LJMj4xxvh6aVan-sNirNUG'

MASTODON_APPLICATION_ID: 4
MASTODON_SCOPES: 'read write follow'
MASTODON_INSTANCE_NAME: 'Redgistry Auth'
MASTODON_GRANT_TYPE: 'client_credentials'
MASTODON_REDIRECT_URI: 'urn:ietf:wg:oauth:2.0:oob'
MASTODON_INSTANCE_URI: 'https://social.redgistry.net'
MASTODON_CLIENT_ID: 'hYmr6CjsInwESY8lwGih875LAn0AM97J8owahnFIxWQ'
MASTODON_CLIENT_SECRET: 'YeSNAfpGwRZc2XyyutmzHcCK9ookMat2gEVdbRBS0ug'

SENDER_NAME: 'No-Reply'
SENDER_EMAIL: 'security-noreply@redgistry.net'

AWS_REGION_NAME: 'us-east-1'
AWS_API_VERSION: '2010-12-01'
AWS_ACCESS_KEY_NAME: 'AKIAT6LJAEBCCVUR7QAC'
AWS_SECRET_KEY_ID: 'b91ahkqVu/Ga2eVWhxIc5dtqkCTLGP+E9lL8K0ce'

SENDER_PHONE: '+18772748398'
TWILIO_AUTH_TOKEN: '9645aec67584d7e7615414bc6b886c28'
TWILIO_ACCOUNT_SID: 'AC6773ef91746b234ebd7d041ca6a646d8'

TWILIO_CHAT_ACCOUNT_SID: 'ACd8128847714a3ab192dbd24b73066ae1'
TWILIO_CHAT_API_KEY: 'SK9afaa0b9fb6629afd43fea9cf66ae51a'
TWILIO_CHAT_API_SECRET: 'LEJYgLOnojabwdFr8bOuhc1O42b9BW6B'
TWILIO_CHAT_SERVICE_SID: 'IS514427018d4548f5875bbbb667a987cf'
TWILIO_CHAT_SYNC_SERVICE_SID: 'default'

DEFAULT_MASTO_PASSWORD: 'redgistry@2023'

FRONTEND_URL: http://localhost:3000
MOBILE_URL: http://localhost:3000
MAIL_SENDER_NAME: 'REDgistry'
MAIL_SENDER_EMAIL: satya@thetransmogrify.in